import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebar: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  cloudDocs: [
    'index',
    {
      type: 'category',
      label: 'Getting started',
      items: [
        {
          type: 'autogenerated',
          dirName: '02_getting-started',
        },
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'autogenerated',
          dirName: '03_guides',
        },
      ],
    },
    {
      type: 'category',
      label: 'Use cases',
      items: [
        {
          type: 'autogenerated',
          dirName: '04_use-cases',
        },
      ],
    },
    {
      type: 'category',
      label: 'Product',
      items: [
        {
          type: 'autogenerated',
          dirName: '05_product',
        },
      ],
    },
    {
      type: 'category',
      label: 'Integrations',
      items: [
        {
          type: 'autogenerated',
          dirName: '06_integrations',
        },
      ],
    },
  ],
};

export default sidebar;
