name: Lint commits

on:
  merge_group:
    types:
      - checks_requested

jobs:
  semantic-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          fetch-depth: 0
      - name: Set up node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22.16'
          cache: npm
      - name: Install dependencies
        run: npm i
      - name: Validate PR commits with commitlint
        run: |
          npx commitlint --from "$(git rev-parse origin/main)" --verbose
